apiVersion: v1
kind: Service
metadata:
  name: livy
  labels:
    app: livy
spec:
  ports:
    - port: 8998
      name: livy-rest
  selector:
    component: livy
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: livy
  labels:
    component: livy
spec:
  selector:
    matchLabels:
      component: livy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: livy
    spec:
      containers:
      - image: showrya619/livy-starrr:latest
        name: livy
        ports:
        - containerPort: 8998
          name: livy-rest
        command: [ "/entrypoint.sh" ]
        args: ["livy-server"]
