version: "3.3"
services:
  spark-master:
    image: sachin/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8083:8083"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8083"
    command: "/Users/onion8/Documents/GitHub/spark_on_kubs/start-master.sh"
  spark-worker:
    image: sachin/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8083
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8083"
    command: "/Users/onion8/Documents/GitHub/spark_on_kubs/start-worker.sh"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
